[alias]
b = "build"
br = "build --release"
brs = "build --profile release-strip"
c = "check"
t = "test"
r = "run"
rr = "run --release"
rrs = "run --profile release-strip"

p = "run --bin prepare"

d0  = "run --bin day0"
d1  = "run --bin day1"
d2  = "run --bin day2"
d3  = "run --bin day3"
d4  = "run --bin day4"
d5  = "run --bin day5"
d6  = "run --bin day6"
d7  = "run --bin day7"
d8  = "run --bin day8"
d9  = "run --bin day9"
d10 = "run --bin day10"
d11 = "run --bin day11"
d12 = "run --bin day12"
d13 = "run --bin day13"
d14 = "run --bin day14"
d15 = "run --bin day15"
d16 = "run --bin day16"
d17 = "run --bin day17"
d18 = "run --bin day18"
d19 = "run --bin day19"
d20 = "run --bin day20"
d21 = "run --bin day21"
d22 = "run --bin day22"
d23 = "run --bin day23"
d24 = "run --bin day24"
d25 = "run --bin day25"

[env]
HELLO = { value = "world" }

[target.'cfg(all())']
rustflags = [
    # https://github.com/EmbarkStudios/rpmalloc-rs/blob/main/.cargo/config.toml
    "-Dunsafe_code",
    "-Wclippy::all",
    "-Wrust_2018_idioms",

    "-Ctarget-cpu=native",
]

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = [
    "-Clink-arg=-fuse-ld=/usr/local/bin/mold",
]

[target.x86_64-pc-windows-msvc]
linker = "lld-link.exe"

rustflags = [
    # manual steps of `static_vcruntime::metabuild();` (static_vcruntime crate)
    "-Ctarget-feature=+crt-static",
    "-Clink-args=/DEFAULTLIB:ucrt.lib /DEFAULTLIB:libvcruntime.lib libcmt.lib",
    "-Clink-args=/NODEFAULTLIB:libvcruntimed.lib /NODEFAULTLIB:vcruntime.lib /NODEFAULTLIB:vcruntimed.lib",
    "-Clink-args=/NODEFAULTLIB:libcmtd.lib /NODEFAULTLIB:msvcrt.lib /NODEFAULTLIB:msvcrtd.lib",
    "-Clink-args=/NODEFAULTLIB:libucrt.lib /NODEFAULTLIB:libucrtd.lib /NODEFAULTLIB:ucrtd.lib",
]
